// src/constants/crops.js
export const crops = {
  Cereals: [
    "Paddy (Rice)",
    "Wheat",
    "Jowar (Sorghum)",
    "Bajra (Pearl Millet)",
    "Ragi (Finger Millet)",
    "Maize (Corn)",
  ],
  Pulses: [
    "Red Gram (Tur/Arhar)",
    "Black Gram (Urad)",
    "Green Gram (Moong)",
    "Bengal Gram (Chana)",
    "Horse Gram",
    "Cowpea",
  ],
  Oilseeds: [
    "Groundnut",
    "Sunflower",
    "Sesame (Til)",
    "Soybean",
    "Mustard",
    "Castor",
  ],
  "Commercial Crops": ["Cotton", "Sugarcane", "Tobacco", "Jute"],
  Vegetables: [
    "Tomato",
    "Onion",
    "Potato",
    "Brinjal",
    "Okra (Bhindi)",
    "Cabbage",
    "Cauliflower",
    "Carrot",
    "Green Chilli",
    "Cucumber",
  ],
  Fruits: [
    "Mango",
    "Banana",
    "Grapes",
    "Pomegranate",
    "Papaya",
    "Orange",
    "Guava",
    "Watermelon",
  ],
  Spices: [
    "Turmeric",
    "Chilli",
    "Ginger",
    "Cardamom",
    "Black Pepper",
    "Coriander",
  ],
};
